package hibernate;
// Generated Jun 4, 2016 6:36:26 PM by Hibernate Tools 4.3.1



/**
 * ConfFldRev generated by hbm2java
 */
public class ConfFldRev  implements java.io.Serializable {


     private ConfFldRevId id;
     private Conference conference;
     private Field field;
     private User user;
     private Integer compentency;

    public ConfFldRev() {
    }

	
    public ConfFldRev(ConfFldRevId id, Conference conference, Field field, User user) {
        this.id = id;
        this.conference = conference;
        this.field = field;
        this.user = user;
    }
    public ConfFldRev(ConfFldRevId id, Conference conference, Field field, User user, Integer compentency) {
       this.id = id;
       this.conference = conference;
       this.field = field;
       this.user = user;
       this.compentency = compentency;
    }
   
    public ConfFldRevId getId() {
        return this.id;
    }
    
    public void setId(ConfFldRevId id) {
        this.id = id;
    }
    public Conference getConference() {
        return this.conference;
    }
    
    public void setConference(Conference conference) {
        this.conference = conference;
    }
    public Field getField() {
        return this.field;
    }
    
    public void setField(Field field) {
        this.field = field;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getCompentency() {
        return this.compentency;
    }
    
    public void setCompentency(Integer compentency) {
        this.compentency = compentency;
    }




}


