package hibernate;
// Generated Jun 4, 2016 6:36:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conference generated by hbm2java
 */
public class Conference  implements java.io.Serializable {


     private Long idConference;
     private User user;
     private String name;
     private String location;
     private Date time;
     private Date applyFrom;
     private Date applyTo;
     private Integer maxDocsPerAuthor;
     private Boolean published;
     private Set<Field> fields = new HashSet<Field>(0);
     private Set<Schedule> schedules = new HashSet<Schedule>(0);
     private Set<ConfFldRev> confFldRevs = new HashSet<ConfFldRev>(0);

    public Conference() {
    }

	
    public Conference(User user) {
        this.user = user;
    }
    public Conference(User user, String name, String location, Date time, Date applyFrom, Date applyTo, Integer maxDocsPerAuthor, Boolean published, Set<Field> fields, Set<Schedule> schedules, Set<ConfFldRev> confFldRevs) {
       this.user = user;
       this.name = name;
       this.location = location;
       this.time = time;
       this.applyFrom = applyFrom;
       this.applyTo = applyTo;
       this.maxDocsPerAuthor = maxDocsPerAuthor;
       this.published = published;
       this.fields = fields;
       this.schedules = schedules;
       this.confFldRevs = confFldRevs;
    }
   
    public Long getIdConference() {
        return this.idConference;
    }
    
    public void setIdConference(Long idConference) {
        this.idConference = idConference;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Date getApplyFrom() {
        return this.applyFrom;
    }
    
    public void setApplyFrom(Date applyFrom) {
        this.applyFrom = applyFrom;
    }
    public Date getApplyTo() {
        return this.applyTo;
    }
    
    public void setApplyTo(Date applyTo) {
        this.applyTo = applyTo;
    }
    public Integer getMaxDocsPerAuthor() {
        return this.maxDocsPerAuthor;
    }
    
    public void setMaxDocsPerAuthor(Integer maxDocsPerAuthor) {
        this.maxDocsPerAuthor = maxDocsPerAuthor;
    }
    public Boolean getPublished() {
        return this.published;
    }
    
    public void setPublished(Boolean published) {
        this.published = published;
    }
    public Set<Field> getFields() {
        return this.fields;
    }
    
    public void setFields(Set<Field> fields) {
        this.fields = fields;
    }
    public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }
    public Set<ConfFldRev> getConfFldRevs() {
        return this.confFldRevs;
    }
    
    public void setConfFldRevs(Set<ConfFldRev> confFldRevs) {
        this.confFldRevs = confFldRevs;
    }




}


