package hibernate;
// Generated Jun 4, 2016 6:36:26 PM by Hibernate Tools 4.3.1



/**
 * ConfFldRevId generated by hbm2java
 */
public class ConfFldRevId  implements java.io.Serializable {


     private long idConference;
     private long idField;
     private long idReviewer;

    public ConfFldRevId() {
    }

    public ConfFldRevId(long idConference, long idField, long idReviewer) {
       this.idConference = idConference;
       this.idField = idField;
       this.idReviewer = idReviewer;
    }
   
    public long getIdConference() {
        return this.idConference;
    }
    
    public void setIdConference(long idConference) {
        this.idConference = idConference;
    }
    public long getIdField() {
        return this.idField;
    }
    
    public void setIdField(long idField) {
        this.idField = idField;
    }
    public long getIdReviewer() {
        return this.idReviewer;
    }
    
    public void setIdReviewer(long idReviewer) {
        this.idReviewer = idReviewer;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConfFldRevId) ) return false;
		 ConfFldRevId castOther = ( ConfFldRevId ) other; 
         
		 return (this.getIdConference()==castOther.getIdConference())
 && (this.getIdField()==castOther.getIdField())
 && (this.getIdReviewer()==castOther.getIdReviewer());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdConference();
         result = 37 * result + (int) this.getIdField();
         result = 37 * result + (int) this.getIdReviewer();
         return result;
   }   


}


