package hibernate;
// Generated Jun 4, 2016 6:36:26 PM by Hibernate Tools 4.3.1



/**
 * ConfRev generated by hbm2java
 */
public class ConfRev  implements java.io.Serializable {


     private ConfRevId id;
     private int count;
     private boolean accepted;

    public ConfRev() {
    }

    public ConfRev(ConfRevId id, int count, boolean accepted) {
       this.id = id;
       this.count = count;
       this.accepted = accepted;
    }
   
    public ConfRevId getId() {
        return this.id;
    }
    
    public void setId(ConfRevId id) {
        this.id = id;
    }
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }
    public boolean isAccepted() {
        return this.accepted;
    }
    
    public void setAccepted(boolean accepted) {
        this.accepted = accepted;
    }




}


