package hibernate;
// Generated Jun 4, 2016 6:36:26 PM by Hibernate Tools 4.3.1



/**
 * ConfRevId generated by hbm2java
 */
public class ConfRevId  implements java.io.Serializable {


     private long idConference;
     private long idReviewer;

    public ConfRevId() {
    }

    public ConfRevId(long idConference, long idReviewer) {
       this.idConference = idConference;
       this.idReviewer = idReviewer;
    }
   
    public long getIdConference() {
        return this.idConference;
    }
    
    public void setIdConference(long idConference) {
        this.idConference = idConference;
    }
    public long getIdReviewer() {
        return this.idReviewer;
    }
    
    public void setIdReviewer(long idReviewer) {
        this.idReviewer = idReviewer;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConfRevId) ) return false;
		 ConfRevId castOther = ( ConfRevId ) other; 
         
		 return (this.getIdConference()==castOther.getIdConference())
 && (this.getIdReviewer()==castOther.getIdReviewer());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdConference();
         result = 37 * result + (int) this.getIdReviewer();
         return result;
   }   


}


