package hibernate;
// Generated Jun 4, 2016 6:36:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Document generated by hbm2java
 */
public class Document  implements java.io.Serializable {


     private Long idDocument;
     private String title;
     private String keywords;
     private String file;
     private Integer status;
     private Date changesdeadline;
     private Set<Review> reviews = new HashSet<Review>(0);
     private Set<User> users = new HashSet<User>(0);
     private Set<Modification> modifications = new HashSet<Modification>(0);
     private Set<Schedule> schedules = new HashSet<Schedule>(0);

    public Document() {
    }

    public Document(String title, String keywords, String file, Integer status, Date changesdeadline, Set<Review> reviews, Set<User> users, Set<Modification> modifications, Set<Schedule> schedules) {
       this.title = title;
       this.keywords = keywords;
       this.file = file;
       this.status = status;
       this.changesdeadline = changesdeadline;
       this.reviews = reviews;
       this.users = users;
       this.modifications = modifications;
       this.schedules = schedules;
    }
   
    public Long getIdDocument() {
        return this.idDocument;
    }
    
    public void setIdDocument(Long idDocument) {
        this.idDocument = idDocument;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getKeywords() {
        return this.keywords;
    }
    
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getChangesdeadline() {
        return this.changesdeadline;
    }
    
    public void setChangesdeadline(Date changesdeadline) {
        this.changesdeadline = changesdeadline;
    }
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }
    public Set<Modification> getModifications() {
        return this.modifications;
    }
    
    public void setModifications(Set<Modification> modifications) {
        this.modifications = modifications;
    }
    public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }




}


