package hibernate;
// Generated Jun 4, 2016 6:36:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Field generated by hbm2java
 */
public class Field  implements java.io.Serializable {


     private Long idField;
     private String name;
     private Set<ConfFldRev> confFldRevs = new HashSet<ConfFldRev>(0);
     private Set<Conference> conferences = new HashSet<Conference>(0);

    public Field() {
    }

	
    public Field(String name) {
        this.name = name;
    }
    public Field(String name, Set<ConfFldRev> confFldRevs, Set<Conference> conferences) {
       this.name = name;
       this.confFldRevs = confFldRevs;
       this.conferences = conferences;
    }
   
    public Long getIdField() {
        return this.idField;
    }
    
    public void setIdField(Long idField) {
        this.idField = idField;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<ConfFldRev> getConfFldRevs() {
        return this.confFldRevs;
    }
    
    public void setConfFldRevs(Set<ConfFldRev> confFldRevs) {
        this.confFldRevs = confFldRevs;
    }
    public Set<Conference> getConferences() {
        return this.conferences;
    }
    
    public void setConferences(Set<Conference> conferences) {
        this.conferences = conferences;
    }




}


