package hibernate;
// Generated Jun 4, 2016 6:36:26 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Modification generated by hbm2java
 */
public class Modification  implements java.io.Serializable {


     private Long idModification;
     private Document document;
     private User user;
     private Date time;
     private String file;

    public Modification() {
    }

    public Modification(Document document, User user, Date time, String file) {
       this.document = document;
       this.user = user;
       this.time = time;
       this.file = file;
    }
   
    public Long getIdModification() {
        return this.idModification;
    }
    
    public void setIdModification(Long idModification) {
        this.idModification = idModification;
    }
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }




}


