package hibernate;
// Generated Jun 4, 2016 6:36:26 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Review generated by hbm2java
 */
public class Review  implements java.io.Serializable {


     private long idReview;
     private Document document;
     private User user;
     private Date due;
     private String comment;
     private Boolean done;

    public Review() {
    }

	
    public Review(long idReview) {
        this.idReview = idReview;
    }
    public Review(long idReview, Document document, User user, Date due, String comment, Boolean done) {
       this.idReview = idReview;
       this.document = document;
       this.user = user;
       this.due = due;
       this.comment = comment;
       this.done = done;
    }
   
    public long getIdReview() {
        return this.idReview;
    }
    
    public void setIdReview(long idReview) {
        this.idReview = idReview;
    }
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDue() {
        return this.due;
    }
    
    public void setDue(Date due) {
        this.due = due;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Boolean getDone() {
        return this.done;
    }
    
    public void setDone(Boolean done) {
        this.done = done;
    }




}


