package hibernate;
// Generated Jun 4, 2016 6:36:26 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Schedule generated by hbm2java
 */
public class Schedule  implements java.io.Serializable {


     private ScheduleId id;
     private Conference conference;
     private Document document;
     private Date time;

    public Schedule() {
    }

	
    public Schedule(ScheduleId id, Conference conference, Document document) {
        this.id = id;
        this.conference = conference;
        this.document = document;
    }
    public Schedule(ScheduleId id, Conference conference, Document document, Date time) {
       this.id = id;
       this.conference = conference;
       this.document = document;
       this.time = time;
    }
   
    public ScheduleId getId() {
        return this.id;
    }
    
    public void setId(ScheduleId id) {
        this.id = id;
    }
    public Conference getConference() {
        return this.conference;
    }
    
    public void setConference(Conference conference) {
        this.conference = conference;
    }
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


