package hibernate;
// Generated Jun 4, 2016 6:36:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Long idUser;
     private String username;
     private String password;
     private String firstname;
     private String lastname;
     private String email;
     private String phone;
     private String org;
     private Date birthdate;
     private String photo;
     private boolean isAuthor;
     private boolean isReviewer;
     private boolean isCoordinator;
     private Set<Document> documents = new HashSet<Document>(0);
     private Set<Conference> conferences = new HashSet<Conference>(0);
     private Set<Modification> modifications = new HashSet<Modification>(0);
     private Set<Review> reviews = new HashSet<Review>(0);
     private Set<ConfFldRev> confFldRevs = new HashSet<ConfFldRev>(0);

    public User() {
    }

	
    public User(boolean isAuthor, boolean isReviewer, boolean isCoordinator) {
        this.isAuthor = isAuthor;
        this.isReviewer = isReviewer;
        this.isCoordinator = isCoordinator;
    }
    public User(String username, String password, String firstname, String lastname, String email, String phone, String org, Date birthdate, String photo, boolean isAuthor, boolean isReviewer, boolean isCoordinator, Set<Document> documents, Set<Conference> conferences, Set<Modification> modifications, Set<Review> reviews, Set<ConfFldRev> confFldRevs) {
       this.username = username;
       this.password = password;
       this.firstname = firstname;
       this.lastname = lastname;
       this.email = email;
       this.phone = phone;
       this.org = org;
       this.birthdate = birthdate;
       this.photo = photo;
       this.isAuthor = isAuthor;
       this.isReviewer = isReviewer;
       this.isCoordinator = isCoordinator;
       this.documents = documents;
       this.conferences = conferences;
       this.modifications = modifications;
       this.reviews = reviews;
       this.confFldRevs = confFldRevs;
    }
   
    public Long getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getOrg() {
        return this.org;
    }
    
    public void setOrg(String org) {
        this.org = org;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public boolean isIsAuthor() {
        return this.isAuthor;
    }
    
    public void setIsAuthor(boolean isAuthor) {
        this.isAuthor = isAuthor;
    }
    public boolean isIsReviewer() {
        return this.isReviewer;
    }
    
    public void setIsReviewer(boolean isReviewer) {
        this.isReviewer = isReviewer;
    }
    public boolean isIsCoordinator() {
        return this.isCoordinator;
    }
    
    public void setIsCoordinator(boolean isCoordinator) {
        this.isCoordinator = isCoordinator;
    }
    public Set<Document> getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set<Document> documents) {
        this.documents = documents;
    }
    public Set<Conference> getConferences() {
        return this.conferences;
    }
    
    public void setConferences(Set<Conference> conferences) {
        this.conferences = conferences;
    }
    public Set<Modification> getModifications() {
        return this.modifications;
    }
    
    public void setModifications(Set<Modification> modifications) {
        this.modifications = modifications;
    }
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }
    public Set<ConfFldRev> getConfFldRevs() {
        return this.confFldRevs;
    }
    
    public void setConfFldRevs(Set<ConfFldRev> confFldRevs) {
        this.confFldRevs = confFldRevs;
    }




}


